import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { ChatWidget } from "./ChatWidget";
afterEach(()=>vi.unstubAllGlobals());
function open(){render(<ChatWidget/>);fireEvent.click(screen.getByRole("button",{name:"Abrir chat"}));return screen.getByLabelText("Tu consulta");}
function send(text="Hola"){fireEvent.change(screen.getByLabelText("Tu consulta"),{target:{value:text}});fireEvent.click(screen.getByRole("button",{name:"Enviar"}));}
it("opens with focus, blocks empty input and closes with Escape/restores focus",()=>{const input=open();expect(input).toHaveFocus();expect(screen.getByRole("button",{name:"Enviar"})).toBeDisabled();fireEvent.keyDown(input,{key:"Escape"});expect(screen.queryByLabelText("Tu consulta")).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"Abrir chat"})).toHaveFocus();});
it("announces waiting, blocks duplicate sends, escapes HTML and keeps successful history after reopen",async()=>{
 let resolve!:(value:unknown)=>void;const fetch=vi.fn<(url: string, options: RequestInit) => Promise<unknown>>(()=>new Promise(r=>{resolve=r}));vi.stubGlobal("fetch",fetch);open();send();expect(screen.getByRole("status")).toHaveTextContent("Consultando");expect(screen.getByRole("button",{name:"Enviando…"})).toBeDisabled();
 await act(async()=>resolve({ok:true,json:async()=>({ok:true,reply:"<img src=x onerror=alert(1)>"})}));expect(screen.getByText("<img src=x onerror=alert(1)>")).toBeInTheDocument();expect(document.querySelector("#chat-panel img")).toBeNull();
 fireEvent.click(screen.getByRole("button",{name:"Cerrar panel del chat"}));fireEvent.click(screen.getByRole("button",{name:"Abrir chat"}));send("¿Y azul?");expect(JSON.parse(fetch.mock.calls[1][1]!.body as string)).toEqual({message:"¿Y azul?",history:[{role:"user",content:"Hola"},{role:"assistant",content:"<img src=x onerror=alert(1)>"}]});
 await act(async()=>resolve({ok:true,json:async()=>({ok:true,reply:"Azul"})}));
});
it("keeps draft on failure and retries manually without failed pairs",async()=>{const fetch=vi.fn().mockResolvedValueOnce({ok:false,json:async()=>({ok:false,message:"Cupo agotado"})}).mockResolvedValueOnce({ok:true,json:async()=>({ok:true,reply:"Respuesta"})});vi.stubGlobal("fetch",fetch);open();send();expect(await screen.findByRole("alert")).toHaveTextContent("Cupo agotado");expect(screen.getByLabelText("Tu consulta")).toHaveValue("Hola");fireEvent.click(screen.getByRole("button",{name:"Enviar"}));await screen.findByText("Respuesta");expect(JSON.parse(fetch.mock.calls[1][1].body).history).toEqual([]);expect(screen.getAllByText("Hola")).toHaveLength(1);});
it("sends only five recent successful pairs",async()=>{const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({ok:true,reply:"Respuesta"})});vi.stubGlobal("fetch",fetch);open();for(let i=0;i<7;i++){send(`Pregunta ${i}`);await waitFor(()=>expect(screen.getByLabelText("Tu consulta")).toHaveValue(""));}const history=JSON.parse(fetch.mock.calls[6][1].body).history;expect(history).toHaveLength(10);expect(history[0].content).toBe("Pregunta 1");});
it("recovers from network errors",async()=>{vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("network secret")));open();send();expect(await screen.findByRole("alert")).not.toHaveTextContent("secret");expect(screen.getByRole("button",{name:"Enviar"})).toBeEnabled();});
it("renders server-rebuilt recommendations with canonical variant links",async()=>{const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({ok:true,reply:"Te recomiendo esta.",recommendations:[{productId:"p1",slug:"camiseta-basica",name:"Camiseta básica",imageUrl:"https://placehold.co/x",categoryName:"Camisetas",priceCents:2190,variant:{id:"v1",size:"M",color:"Azul",priceCents:2190,stock:2}}]})});vi.stubGlobal("fetch",fetch);open();send("Recomiéndame algo");expect(await screen.findByText("Te recomiendo esta.")).toBeInTheDocument();const link=screen.getByRole("link",{name:/Camiseta básica/});expect(link).toHaveAttribute("href","/products/camiseta-basica?size=M&color=Azul");expect(screen.getByText(/2.*disponibles/)).toBeInTheDocument();});
it("keeps earlier recommendation cards when a follow-up fails",async()=>{const fetch=vi.fn().mockResolvedValueOnce({ok:true,json:async()=>({ok:true,reply:"Te recomiendo esta.",recommendations:[{productId:"p1",slug:"camiseta-basica",name:"Camiseta básica",imageUrl:"https://placehold.co/x",categoryName:"Camisetas",priceCents:2190,variant:null}]})}).mockResolvedValueOnce({ok:false,json:async()=>({ok:false,message:"Cupo agotado"})});vi.stubGlobal("fetch",fetch);open();send("Recomiéndame algo");expect(await screen.findByRole("link",{name:/Camiseta básica/})).toBeInTheDocument();send("¿Y otra?");expect(await screen.findByRole("alert")).toHaveTextContent("Cupo agotado");expect(screen.getByRole("link",{name:/Camiseta básica/})).toBeInTheDocument();});
it("rejects malformed recommendation array items",async()=>{const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({ok:true,reply:"Respuesta",recommendations:[{productId:"p1"}]})});vi.stubGlobal("fetch",fetch);open();send();expect(await screen.findByRole("alert")).toHaveTextContent("no está disponible");expect(screen.queryByRole("link")).not.toBeInTheDocument();});
it("rejects a present non-array recommendation payload",async()=>{const fetch=vi.fn().mockResolvedValue({ok:true,json:async()=>({ok:true,reply:"Respuesta",recommendations:{productId:"p1"}})});vi.stubGlobal("fetch",fetch);open();send();expect(await screen.findByRole("alert")).toHaveTextContent("no está disponible");expect(screen.queryByRole("link")).not.toBeInTheDocument();});
